### ISSUE TITLE
Can't build due to INAppStoreWindow pod spec

### ISSUE THREAD

**Issue by aknuds1** [sonoramac/Sonora#62]
When attempting to install dependencies via CocoaPods, prior to building Sonora itself, it breaks due to an issue in INAppStoreWindow.podspec:

    ➜  Sonora git:(master) ✗ pod install
    Analyzing dependencies
    Pre-downloading: `INAppStoreWindow` from `git://github.com/sonoramac/INAppStoreWindow.git`

    [!] Invalid `INAppStoreWindow.podspec` file: [!] [INAppStoreWindow (1.2)] Clean paths are deprecated. CocoaPods now cleans unused files by default. Use the `preserve_paths` attribute if needed.. Updating CocoaPods might fix the issue.

     #  from /Users/arve/Projects/Sonora/Pods/Local Podspecs/INAppStoreWindow.podspec:9
     #  -------------------------------------------
     #  	s.source   		= { :git => 'https://github.com/indragiek/INAppStoreWindow.git', :tag => 'v1.2' }
     >  	s.clean_paths	= 'SampleApp'
     #  	s.platform 		= :osx
     #  -------------------------------------------

**Comment by Keithbsmiley** [comment]
Fixed in https://github.com/sonoramac/Sonora/pull/63
